# Generated by Django 3.0.6 on 2020-06-23 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 10, 46, 2, 780532)),
        ),
    ]
