# Generated by Django 3.0.5 on 2020-06-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_employes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='date',
        ),
    ]
